# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand.

createComputeChecksumArgs <- function(incremental = TRUE,
                                      generateStats = TRUE) {
  analysis <- list()
  for (name in names(formals(createComputeChecksumArgs))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortGeneratorModule",
                         version = "0.0.7",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortGeneratorModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
