# Copyright 2023 Observational Health Data Sciences and Informatics
#
# This file is part of CohortGeneratorModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code:
styler::style_dir()
OhdsiRTools::updateCopyrightYearFolder()
OhdsiRTools::findNonAsciiStringsInFolder()

# Generate settings function
moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
message(sprintf("Using module version '%s' in settings function.", moduleInfo$Version))
library(CohortGenerator)
rCode <- c("# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. ")
rCode <- c(rCode, readLines("extras/SettingsFunctionsStub.R"))
rCode <- gsub("%module%", moduleInfo$Name, rCode)
rCode <- gsub("%version%", moduleInfo$Version, rCode)
writeLines(rCode, "SettingsFunctions.R")

# Generate renv lock file and activate renv:
renv::deactivate()
OhdsiRTools::createRenvLockFile(
  rootPackage = "CohortGenerator",
  includeRootPackage = TRUE,
  mode = "description",
  additionalRequiredPackages = c(
    "DatabaseConnector",
    "checkmate",
    "CirceR",
    "testthat",
    "Eunomia"
  )
)
renv::init()

# Sync lock files with HADES-wide lock file
renv::snapshot()
renv::activate(profile = "dev")
renv::activate(profile = NULL)
hadesWideLockFileName <- normalizePath(file.path("renv", "profiles", "dev", "renv.lock"))
unlink(hadesWideLockFileName)
utils::download.file(
  url = "https://raw.githubusercontent.com/OHDSI/Hades/main/hadesWideReleases/2023Q3/renv.lock",
  destfile = hadesWideLockFileName
)
hadesWideLockFile <- renv::lockfile_read(
  file = hadesWideLockFileName
)
projectRenvLockFile <- renv::lockfile_read(
  fileName = "renv.lock"
)
# hadesWideLockFile <- ParallelLogger::loadSettingsFromJson(
#   fileName = hadesWideLockFileName
# )
# projectRenvLockFile <- ParallelLogger::loadSettingsFromJson(
#   fileName = "renv.lock"
# )

# Set the R version
projectRenvLockFile$R$Version <- hadesWideLockFile$R$Version

# Verify the package versions across lock files
projectPackages <- data.frame()
for (i in 1:length(projectRenvLockFile$Packages)) {
  projectPackages <- rbind(
    projectPackages,
    data.frame(
      projectPackageName = projectRenvLockFile$Packages[[i]]$Package,
      projectPackageVersion = projectRenvLockFile$Packages[[i]]$Version,
      projectPackageRemoteRef = ifelse(is.null(projectRenvLockFile$Packages[[i]]$RemoteRef), yes = NA, no = projectRenvLockFile$Packages[[i]]$RemoteRef)
    )
  )
}
hadesWideLockFilePackages <- data.frame()
for (i in 1:length(hadesWideLockFile$Packages)) {
  hadesWideLockFilePackages <- rbind(
    hadesWideLockFilePackages,
    data.frame(
      hwlfPackageName = hadesWideLockFile$Packages[[i]]$Package,
      hwlfPackageVersion = hadesWideLockFile$Packages[[i]]$Version,
      hwlfPackageRemoteRef = ifelse(is.null(hadesWideLockFile$Packages[[i]]$RemoteRef), yes = NA, no = hadesWideLockFile$Packages[[i]]$RemoteRef)
    )
  )
}

mergedLockFilePackages <- merge(
  x = projectPackages,
  y = hadesWideLockFilePackages,
  by.x = "projectPackageName",
  by.y = "hwlfPackageName"
)

findPackageByName <- function(list, packageName) {
  index <- which(sapply(list, function(x) x$Package == packageName))
  return(index)
}

verDiffs <- mergedLockFilePackages[mergedLockFilePackages$projectPackageVersion != mergedLockFilePackages$hwlfPackageVersion,]
for (i in 1:nrow(verDiffs)) {
  index <- findPackageByName(projectRenvLockFile$Packages, verDiffs[i,]$projectPackageName)
  projectRenvLockFile$Packages[[index]]$Version <- verDiffs[i,]$hwlfPackageVersion
  if (!is.na(verDiffs[i,]$hwlfPackageRemoteRef)) {
    projectRenvLockFile$Packages[[index]]$RemoteRef <- verDiffs[i,]$hwlfPackageRemoteRef
  }
}

renv::lockfile_write(
  lockfile = projectRenvLockFile,
  file = "renv.lock"
)
# One off updates
renv::record("OHDSI/CirceR@v1.3.2")
renv::record("OHDSI/CirceR@v1.3.2", lockfile = hadesWideLockFileName)
renv::record("OHDSI/ResultModelManager@v0.5.6")
renv::record("OHDSI/ResultModelManager@v0.5.6", lockfile = hadesWideLockFileName)

# Mandatory Strategus dependencies: CohortGenerator, DatabaseConnector, keyring, ParallelLogger, renv, SqlRender
mandatoryPackages <- list(
  CohortGenerator = list(
    Package = "CohortGenerator",
    Version = "0.8.1",
    Source = "GitHub",
    RemoteType = "github",
    RemoteHost = "api.github.com",
    RemoteUsername = "OHDSI",
    RemoteRepo = "CohortGenerator",
    RemoteRef = "v0.8.1",
    RemoteSha = "78757f1b191a395cf9dcff0d5bbe2b9fa4aa163e"
  ),
  DBI = list(
    Package = "DBI",
    Version = "1.2.1",
    Source = "Repository",
    Repository = "CRAN"
  ),
  DatabaseConnector = list(
    Package = "DatabaseConnector",
    Version = "6.3.2",
    Source = "Repository",
    Repository = "CRAN"
  ),
  keyring = list(
    Package = "keyring",
    Version = "1.3.2",
    Source = "Repository",
    Repository = "CRAN"
  ),
  ParallelLogger = list(
    Package = "ParallelLogger",
    Version = "3.3.0",
    Source = "Repository",
    Repository = "CRAN"
  ),
  renv = list(
    Package = "renv",
    Version = "1.0.3",
    Source = "Repository",
    Repository = "CRAN"
  ),
  RSQLite = list(
    Package = "RSQLite",
    Version = "2.3.5",
    Source = "Repository",
    Repository = "CRAN"
  ),
  SqlRender = list(
    Package = "SqlRender",
    Version = "1.16.1",
    Source = "Repository",
    Repository = "CRAN"
  )
)
renv::record(mandatoryPackages)
renv::record(mandatoryPackages, lockfile = hadesWideLockFileName)